package br.com.simplificarural.navigation

object RuralRoutes {
    const val HOME = "home"
    const val ANIMALS = "animals"
    const val BIRDS = "birds"
    const val BIRD_EGGS = "bird_eggs"
    const val BIRD_LOTS = "bird_lots"
    const val CATTLE = "cattle"
    const val CATTLE_LIST = "cattle_list"
    const val CATTLE_DETAIL = "cattle_detail"
    const val CATTLE_MILK = "cattle_milk"
    const val CATTLE_FEED = "cattle_feed"
    const val CATTLE_NEW = "cattle_new"
    const val SWINE = "swine"
    const val SWINE_FATTENING = "swine_fattening"
    const val SWINE_LOTS = "swine_lots"
    const val SWINE_BREEDING = "swine_breeding"
    const val SOW_DETAIL = "sow_detail"
    const val SWINE_WEIGHT = "swine_weight"
    const val SWINE_FARROWING = "swine_farrowing"
    const val STOCK = "stock"
    const val STOCK_DETAIL = "stock_detail"
    const val FINANCE = "finance"
    const val ENTRY = "entry"
    const val EXPENSE = "expense"
    const val PURCHASES = "purchases"
    const val NEW_PURCHASE = "new_purchase"
    const val SALES = "sales"
    const val NEW_SALE = "new_sale"
    const val AGENDA = "agenda"
    const val HEALTH = "health"
    const val PRODUCTION = "production"
    const val STOCK_ADD = "stock_add"
    const val MORE = "more"
    const val SETTINGS = "settings"
    const val ACTIVITIES = "activities"
    const val ASSISTANT = "assistant"
    const val OPERATIONAL_TEST = "operational_test"
    const val GENERIC = "generic"
    const val FEATURE_PREFIX = "feature/"
    fun feature(name: String): String = "$FEATURE_PREFIX$name"
    fun stockDetail(product: String): String = "$STOCK_DETAIL/$product"
    fun stockAdd(category: String): String = "$STOCK_ADD/$category"
    fun cattleDetail(id: String): String = "$CATTLE_DETAIL/$id"
}
